### ISSUE TITLE
The trait diesel::Expression is not implemented for diesel_ltree::Ltree

### ISSUE THREAD

**Issue by dbikic** [kivikakk/diesel_ltree#23]
Hello, 

I have a project which uses `diesel` 1.4.8 and `diesel_tree` 0.2.4, and I want to updated them to the latest versions. However, I'm blocked by the following compilation issue:

```
#[derive(Debug, Insertable)]
   |                 ^^^^^^^^^^ the trait `diesel::Expression` is not implemented for `diesel_ltree::Ltree`
```

Any idea what is wrong here, and if there is anything I can do to fix this?

**Comment by kivikakk** [comment]
Can you let me know how I can reproduce this same compile error locally? What do your project's `Cargo.toml` and `Cargo.lock` look like? (or at least all the lines related to Diesel/diesel_ltree.)  What line of which file is actually shown there?

I've spent half an hour trying to reproduce what I thought the problem _would_ be, given what you've described, but no luck. Let me know!

**Comment by TheConner** [comment]
I ran into this problem, given the lack of MWE I think I can help out by [contributing one](https://github.com/TheConner/diesel-ltree-mwe). The problem here seems to be with how `diesel_ltree` interacts with the code generated by Diesel. In my MWE, [this table](https://github.com/TheConner/diesel-ltree-mwe/blob/main/migrations/2023-01-01-170717_init/up.sql)

```sql
CREATE TABLE foo (
  id SERIAL PRIMARY KEY,
  tree_path LTREE NOT NULL
);
```
Ends up creating the following [`schema.rs`](https://github.com/TheConner/diesel-ltree-mwe/blob/main/src/schema.rs):
```rs
// @generated automatically by Diesel CLI.

pub mod sql_types {
    #[derive(diesel::sql_types::SqlType)]
    #[diesel(postgres_type(name = "ltree"))]
    pub struct Ltree;
}

diesel::table! {
    use diesel::sql_types::*;
    use super::sql_types::Ltree;

    foo (id) {
        id -> Int4,
        tree_path -> Ltree,
    }
}
```

And in its current state, if you attempt to do anything with the `foo` table (select, insert etc) you will end up with the errors reported by the poster. If you replace `use super::sql_types::Ltree;` with `diesel_ltree::sql_types::Ltree;`, all of the traits implemented by `diesel_ltree` are picked up and everything works fine.

**Comment by TheConner** [comment]
A potential workaround is to tell Diesel not to generate [missing SQL type definitions](https://diesel.rs/guides/configuring-diesel-cli.html) and then manually specify them yourself. For my MWE the diesel.toml will become

```toml
[print_schema]
file = "src/schema.rs"
generate_missing_sql_type_definitions = false
import_types = ["diesel::sql_types::*", "diesel_ltree::sql_types::Ltree"]
```
And then the schema generated by diesel will work fine.

**Comment by kivikakk** [comment]
Oof, I see. It looks like this is the best we can do with `print_schema`, so I'd say `import_types` + `patch_file` is indeed the path forward for such uses.

In #25 I'm updating the built-in tests to use this instead of issuing `table!` manually.

@TheConner — thank you _so_ much for putting that example together! I appreciate it a heap. :heart:
